AdminConsole/AdminConsole/Models/TargetContainer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdminConsole.Models
{
    public partial class TargetContainer
    {
        public TargetContainer()
        {
            this.ChildTargetContainers = new HashSet<TargetContainer>();
            this.Targets = new HashSet<Target>();
        }
    
        [Key]
        public int Id { get; set; }
        public string Description { get; set; }
        public short Sequence { get; set; }
        public bool InheritsParent { get; set; }
        public string ExtendedProperty { get; set; }
        public int? ParentTargetContainer_Id { get; set; }
        public string DesktopType_DesktopCode { get; set; }
    
        [ForeignKey("DesktopType_DesktopCode")]
        public virtual Desktop Desktop { get; set; }

        public virtual ICollection<TargetContainer> ChildTargetContainers { get; set; }

        
        [ForeignKey("ParentTargetContainer_Id")]
        public virtual TargetContainer ParentTargetContainer { get; set; }

        public virtual ICollection<Target> Targets { get; set; }
    }
    
}

AdminConsole/AdminConsole/Controllers/SiteMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;

namespace AdminConsole.Controllers
{
    public class SiteMapController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /SiteMap/

        public ActionResult Index(String desktopType)
        {
            return View();
        }

        public ViewResult SiteMap()
        {
            return View(db.DesktopTypes.ToList());
        }

    }
}

AdminConsole/AdminConsole/Controllers/TargetContainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;

namespace AdminConsole.Controllers
{ 
    public class TargetContainerController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /TargetContainer/

        public ViewResult Index()
        {
            var targetcontainers = db.TargetContainers.Include(t => t.Desktop).Include(t => t.ParentTargetContainer);
            return View(targetcontainers.ToList());
        }

        //
        // GET: /TargetContainer/Details/5

        public ViewResult Details(int? id)
        {
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            return View(targetcontainer);
        }

        //
        // GET: /TargetContainer/Create

        public ActionResult Create(String desktopType, int? parentContainerId = null)
        {
            //ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description");
            //ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description");


            ViewBag.DesktopType_DesktopCode = desktopType;
            ViewBag.ParentTargetContainer_Id = parentContainerId;
            return View();

            //return View(new TargetContainer() { Desktop = db.DesktopTypes.Find(desktopType) });
        } 

        //
        // POST: /TargetContainer/Create

        [HttpPost]
        public ActionResult Create(TargetContainer targetcontainer)
        {
            //ModelState.Clear();

            //targetcontainer.DesktopType = db.DesktopTypes.Find(targetcontainer.DesktopType_DesktopCode);
            //TryValidateModel(targetcontainer);

            if (ModelState.IsValid)
            {
                db.TargetContainers.Add(targetcontainer);
                db.SaveChanges();
                return RedirectToAction("Index", "SiteMap");
            }
            else
            {
                ViewData.Add("Error", String.Join(";", ModelState.Values.SelectMany(value => value.Errors).Select(
                    error => !String.IsNullOrEmpty(error.ErrorMessage) ? error.ErrorMessage : error.Exception != null ? error.Exception.Message : "" )));
            }

            //ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description", targetcontainer.DesktopType_DesktopCode);
            //ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description", targetcontainer.ParentTargetContainer_Id);
            return View(targetcontainer);
        }
        
        //
        // GET: /TargetContainer/Edit/5
 
        public ActionResult Edit(int id)
        {
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description", targetcontainer.DesktopType_DesktopCode);
            ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description", targetcontainer.ParentTargetContainer_Id);
            return View(targetcontainer);
        }

        //
        // POST: /TargetContainer/Edit/5

        [HttpPost]
        public ActionResult Edit(TargetContainer targetcontainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(targetcontainer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "SiteMap");
            }
            //ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description", targetcontainer.DesktopType_DesktopCode);
            //ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description", targetcontainer.ParentTargetContainer_Id);
            return View(targetcontainer);
        }

        //
        // GET: /TargetContainer/Delete/5
 
        public ActionResult Delete(int id)
        {
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            return View(targetcontainer);
        }

        //
        // POST: /TargetContainer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            db.TargetContainers.Remove(targetcontainer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AdminConsole/AdminConsole/Controllers/TargetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;

namespace AdminConsole.Controllers
{ 
    public class TargetController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /Target/

        public ViewResult Index()
        {
            var targets = db.Targets.Include(t => t.TargetType);
            return View(targets.ToList());
        }

        //
        // GET: /Target/Details/5

        public ViewResult Details(int id)
        {
            Target target = db.Targets.Find(id);
            return View(target);
        }

        //
        // GET: /Target/Create

        public ActionResult Create(int targetContainerId)
        {
            //Target target = new Target();
            //target.TargetContainers.Add(db.TargetContainers.Find(targetContainerId));

            ViewBag.TargetContainerId = targetContainerId;
            ViewBag.TargetType_TargetTypeCode = new SelectList(db.TargetTypes, "TargetTypeCode", "Description");
            return View();
        } 

        //
        // POST: /Target/Create

        [HttpPost]
        public ActionResult Create(Target target)
        {
            target.TargetContainers.Add(db.TargetContainers.Find(Int32.Parse(Request["TargetContainerId"])));

            if (ModelState.IsValid)
            {
                db.Targets.Add(target);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.TargetType_TargetTypeCode = new SelectList(db.TargetTypes, "TargetTypeCode", "Description", target.TargetType_TargetTypeCode);
            return View(target);
        }
        
        //
        // GET: /Target/Edit/5
 
        public ActionResult Edit(int id)
        {
            Target target = db.Targets.Find(id);
            ViewBag.TargetType_TargetTypeCode = new SelectList(db.TargetTypes, "TargetTypeCode", "Description", target.TargetType_TargetTypeCode);
            return View(target);
        }

        //
        // POST: /Target/Edit/5

        [HttpPost]
        public ActionResult Edit(Target target)
        {
            if (ModelState.IsValid)
            {
                db.Entry(target).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TargetType_TargetTypeCode = new SelectList(db.TargetTypes, "TargetTypeCode", "Description", target.TargetType_TargetTypeCode);
            return View(target);
        }

        //
        // GET: /Target/Delete/5
 
        public ActionResult Delete(int id)
        {
            Target target = db.Targets.Find(id);
            return View(target);
        }

        //
        // POST: /Target/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Target target = db.Targets.Find(id);
            db.Targets.Remove(target);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AdminConsole/AdminConsole/Views/TargetContainer/Create.cshtml
@model AdminConsole.Models.TargetContainer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@if (ViewData.ContainsKey("Error"))
{
    <div style="color:Red">
        @(ViewData["Error"].ToString())
    </div>    
}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>TargetContainer</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sequence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sequence)
            @Html.ValidationMessageFor(model => model.Sequence)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.InheritsParent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.InheritsParent)
            @Html.ValidationMessageFor(model => model.InheritsParent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExtendedProperty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExtendedProperty)
            @Html.ValidationMessageFor(model => model.ExtendedProperty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParentTargetContainer_Id, "ParentTargetContainer")
        </div>
        <div class="editor-field">
            @Html.DisplayText("ParentTargetContainer_Id")
            @Html.Hidden("ParentTargetContainer_Id")
@*            @Html.EditorFor(model => model.ParentTargetContainer_Id)
*@            @Html.ValidationMessageFor(model => model.ParentTargetContainer_Id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DesktopType_DesktopCode, "DesktopType")
        </div>
        <div class="editor-field">
            @Html.DisplayText("DesktopType_DesktopCode")
            @Html.Hidden("DesktopType_DesktopCode")
            
@*            @Html.DropDownList("DesktopType_DesktopCode", String.Empty)
*@            @Html.ValidationMessageFor(model => model.DesktopType_DesktopCode)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    @Html.ActionLink("Back to Sitemap", "Index", "SiteMap", new { desktopType= ("DesktopType_DesktopCode")}, null)
</div>

AdminConsole/AdminConsole/Views/TargetContainer/Delete.cshtml
@model AdminConsole.Models.TargetContainer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TargetContainer</legend>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">Sequence</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sequence)
    </div>

    <div class="display-label">InheritsParent</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InheritsParent)
    </div>

    <div class="display-label">ExtendedProperty</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExtendedProperty)
    </div>

    <div class="display-label">TargetContainer1</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TargetContainer1.Description)
    </div>

    <div class="display-label">DesktopType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DesktopType.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

AdminConsole/AdminConsole/Views/TargetContainer/Details.cshtml
@{
    Layout = null;
}
@model AdminConsole.Models.TargetContainer
<!DOCTYPE html>
<html>
<body>
    <h2>Details</h2>

    @if (Model != null)
    {
        <table>
            <tr>                              
                <th>
                    Description</th>
                <th>
                    Sequence</th>
                <th>
                    InheritsParent</th>
                <th>
                    ExtendedProperty</th>
                <th>
                    TargetContainer1</th>
                <th>
                    DesktopType</th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Description)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Sequence)
                </td>
                <td>
                    @Html.DisplayFor(model => model.InheritsParent)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ExtendedProperty)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ParentTargetContainer.Description)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Desktop.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
                </td>
                <td>
                    @Html.ActionLink("Add Target", "Create", "Target", new { targetContainerId = Model.Id }, null)
                </td>
            </tr>
        </table>
        
        
        <table>
            <tr>
                <th>Id</th>
                <th>Address</th>
                <th>TargetType</th>
            </tr>
            @foreach (var target in Model.Targets)
            {
                <tr>
                    <td> @(target.Id) </td>
                    <td> @(target.Address) </td>
                    <td> @(target.TargetType.TargetTypeCode) </td>
                </tr>
            }
        </table>
    }
</body>
</html>

AdminConsole/AdminConsole/Views/TargetContainer/Edit.cshtml
@model AdminConsole.Models.TargetContainer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>TargetContainer</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sequence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sequence)
            @Html.ValidationMessageFor(model => model.Sequence)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.InheritsParent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.InheritsParent)
            @Html.ValidationMessageFor(model => model.InheritsParent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExtendedProperty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExtendedProperty)
            @Html.ValidationMessageFor(model => model.ExtendedProperty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParentTargetContainer_Id, "TargetContainer1")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ParentTargetContainer_Id", String.Empty)
            @Html.ValidationMessageFor(model => model.ParentTargetContainer_Id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DesktopType_DesktopCode, "DesktopType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DesktopType_DesktopCode", String.Empty)
            @Html.ValidationMessageFor(model => model.DesktopType_DesktopCode)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AdminConsole/AdminConsole/Views/TargetContainer/Index.cshtml
@model IEnumerable<AdminConsole.Models.TargetContainer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Description
        </th>
        <th>
            Sequence
        </th>
        <th>
            InheritsParent
        </th>
        <th>
            ExtendedProperty
        </th>
        <th>
            TargetContainer1
        </th>
        <th>
            DesktopType
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sequence)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InheritsParent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExtendedProperty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ParentTargetContainer.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Desktop.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>