AdminConsole/AdminConsole/Models/Desktop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdminConsole.Models
{
    public partial class Desktop
    {
        public Desktop()
        {
            this.TargetContainers = new HashSet<TargetContainer>();
        }
    
        [Key]
        public string DesktopCode { get; set; }
        public string Description { get; set; }
        public string ExtendedProperty { get; set; }
    
        public virtual ICollection<TargetContainer> TargetContainers { get; set; }
    }
    
}

AdminConsole/AdminConsole/Controllers/DesktopController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;
using System.Data.Entity.Validation;
using System.Text;
using System.Web.Routing;

namespace AdminConsole.Controllers
{ 
    public class DesktopController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /Desktop/

        public ViewResult Index()
        {
            return View(db.DesktopTypes.ToList());
        }

        //
        // GET: /Desktop/Details/5

        public ViewResult Details(string id)
        {
            Desktop desktoptype = db.DesktopTypes.Find(id);
            return View(desktoptype);
        }

        //
        // GET: /Desktop/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Desktop/Create

        [HttpPost]
        public ActionResult Create(Desktop desktoptype)
        {
            if (ModelState.IsValid)
            {
                db.DesktopTypes.Add(desktoptype);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    StringBuilder routeValues = new StringBuilder();
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            routeValues.AppendFormat("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            //Trace.TraceInformation("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                    ViewData.Add("Error", routeValues.ToString());
                    return View();
                    //return RedirectToAction("Create");
                    //return RedirectToAction("Create", new RouteValueDictionary(new Dictionary<String, String>{ {"Error", routeValues.ToString()} }));
                }
                return RedirectToAction("Index");  
            }

            return View(desktoptype);
        }
        
        //
        // GET: /Desktop/Edit/5
 
        public ActionResult Edit(string id)
        {
            Desktop desktoptype = db.DesktopTypes.Find(id);
            return View(desktoptype);
        }

        //
        // POST: /Desktop/Edit/5

        [HttpPost]
        public ActionResult Edit(Desktop desktoptype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(desktoptype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(desktoptype);
        }

        //
        // GET: /Desktop/Delete/5
 
        public ActionResult Delete(string id)
        {
            Desktop desktoptype = db.DesktopTypes.Find(id);
            return View(desktoptype);
        }

        //
        // POST: /Desktop/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {            
            Desktop desktoptype = db.DesktopTypes.Find(id);
            db.DesktopTypes.Remove(desktoptype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AdminConsole/AdminConsole/Controllers/SiteMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;

namespace AdminConsole.Controllers
{
    public class SiteMapController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /SiteMap/

        public ActionResult Index(String desktopType)
        {
            return View();
        }

        public ViewResult SiteMap()
        {
            return View(db.DesktopTypes.ToList());
        }

    }
}

AdminConsole/AdminConsole/Views/Desktop/Create.cshtml
@model AdminConsole.Models.Desktop

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@if (ViewData.ContainsKey("Error"))
{
    <div style="color:Red">
        @(ViewData["Error"].ToString())
    </div>    
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>DesktopType</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.DesktopCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DesktopCode)
            @Html.ValidationMessageFor(model => model.DesktopCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExtendedProperty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExtendedProperty)
            @Html.ValidationMessageFor(model => model.ExtendedProperty)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AdminConsole/AdminConsole/Views/Desktop/Delete.cshtml
@model AdminConsole.Models.DesktopType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>DesktopType</legend>

    <div class="display-label">DesktopCode</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DesktopCode)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">ExtendedProperty</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExtendedProperty)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

AdminConsole/AdminConsole/Views/Desktop/Details.cshtml
@model AdminConsole.Models.DesktopType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>DesktopType</legend>

    <div class="display-label">DesktopCode</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DesktopCode)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">ExtendedProperty</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExtendedProperty)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdminConsole/AdminConsole/Views/Desktop/Edit.cshtml
@model AdminConsole.Models.DesktopType

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>DesktopType</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.DesktopCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DesktopCode)
            @Html.ValidationMessageFor(model => model.DesktopCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExtendedProperty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExtendedProperty)
            @Html.ValidationMessageFor(model => model.ExtendedProperty)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AdminConsole/AdminConsole/Views/Desktop/Index.cshtml
@model IEnumerable<AdminConsole.Models.Desktop>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            DesktopCode
        </th>
        <th>
            Description
        </th>
        <th>
            ExtendedProperty
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DesktopCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExtendedProperty)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Show", "Index", "SiteMap", new { desktopType=item.DesktopCode }, null)
        </td>
    </tr>
}

</table>