AdminConsole/AdminConsole/Controllers/DesktopController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;
using System.Data.Entity.Validation;
using System.Text;
using System.Web.Routing;

namespace AdminConsole.Controllers
{ 
    public class DesktopController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /Desktop/

        public ViewResult Index()
        {
            return View(db.DesktopTypes.ToList());
        }

        //
        // GET: /Desktop/Details/5

        public ViewResult Details(string id)
        {
            Desktop desktoptype = db.DesktopTypes.Find(id);
            return View(desktoptype);
        }

        //
        // GET: /Desktop/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Desktop/Create

        [HttpPost]
        public ActionResult Create(Desktop desktoptype)
        {
            if (ModelState.IsValid)
            {
                db.DesktopTypes.Add(desktoptype);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    StringBuilder routeValues = new StringBuilder();
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            routeValues.AppendFormat("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            //Trace.TraceInformation("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                    ViewData.Add("Error", routeValues.ToString());
                    return View();
                    //return RedirectToAction("Create");
                    //return RedirectToAction("Create", new RouteValueDictionary(new Dictionary<String, String>{ {"Error", routeValues.ToString()} }));
                }
                return RedirectToAction("Index");  
            }

            return View(desktoptype);
        }
        
        //
        // GET: /Desktop/Edit/5
 
        public ActionResult Edit(string id)
        {
            Desktop desktoptype = db.DesktopTypes.Find(id);
            return View(desktoptype);
        }

        //
        // POST: /Desktop/Edit/5

        [HttpPost]
        public ActionResult Edit(Desktop desktoptype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(desktoptype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(desktoptype);
        }

        //
        // GET: /Desktop/Delete/5
 
        public ActionResult Delete(string id)
        {
            Desktop desktoptype = db.DesktopTypes.Find(id);
            return View(desktoptype);
        }

        //
        // POST: /Desktop/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {            
            Desktop desktoptype = db.DesktopTypes.Find(id);
            db.DesktopTypes.Remove(desktoptype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AdminConsole/AdminConsole/Controllers/SiteMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;

namespace AdminConsole.Controllers
{
    public class SiteMapController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /SiteMap/

        public ActionResult Index(String desktopType)
        {
            return View();
        }

        public ViewResult SiteMap()
        {
            return View(db.DesktopTypes.ToList());
        }

    }
}

AdminConsole/AdminConsole/Controllers/TargetContainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminConsole.Models;

namespace AdminConsole.Controllers
{ 
    public class TargetContainerController : Controller
    {
        private AdminConsoleEntities db = new AdminConsoleEntities();

        //
        // GET: /TargetContainer/

        public ViewResult Index()
        {
            var targetcontainers = db.TargetContainers.Include(t => t.Desktop).Include(t => t.ParentTargetContainer);
            return View(targetcontainers.ToList());
        }

        //
        // GET: /TargetContainer/Details/5

        public ViewResult Details(int? id)
        {
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            return View(targetcontainer);
        }

        //
        // GET: /TargetContainer/Create

        public ActionResult Create(String desktopType, int? parentContainerId = null)
        {
            //ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description");
            //ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description");


            ViewBag.DesktopType_DesktopCode = desktopType;
            ViewBag.ParentTargetContainer_Id = parentContainerId;
            return View();

            //return View(new TargetContainer() { Desktop = db.DesktopTypes.Find(desktopType) });
        } 

        //
        // POST: /TargetContainer/Create

        [HttpPost]
        public ActionResult Create(TargetContainer targetcontainer)
        {
            //ModelState.Clear();

            //targetcontainer.DesktopType = db.DesktopTypes.Find(targetcontainer.DesktopType_DesktopCode);
            //TryValidateModel(targetcontainer);

            if (ModelState.IsValid)
            {
                db.TargetContainers.Add(targetcontainer);
                db.SaveChanges();
                return RedirectToAction("Index", "SiteMap");
            }
            else
            {
                ViewData.Add("Error", String.Join(";", ModelState.Values.SelectMany(value => value.Errors).Select(
                    error => !String.IsNullOrEmpty(error.ErrorMessage) ? error.ErrorMessage : error.Exception != null ? error.Exception.Message : "" )));
            }

            //ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description", targetcontainer.DesktopType_DesktopCode);
            //ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description", targetcontainer.ParentTargetContainer_Id);
            return View(targetcontainer);
        }
        
        //
        // GET: /TargetContainer/Edit/5
 
        public ActionResult Edit(int id)
        {
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description", targetcontainer.DesktopType_DesktopCode);
            ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description", targetcontainer.ParentTargetContainer_Id);
            return View(targetcontainer);
        }

        //
        // POST: /TargetContainer/Edit/5

        [HttpPost]
        public ActionResult Edit(TargetContainer targetcontainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(targetcontainer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "SiteMap");
            }
            //ViewBag.DesktopType_DesktopCode = new SelectList(db.DesktopTypes, "DesktopCode", "Description", targetcontainer.DesktopType_DesktopCode);
            //ViewBag.ParentTargetContainer_Id = new SelectList(db.TargetContainers, "Id", "Description", targetcontainer.ParentTargetContainer_Id);
            return View(targetcontainer);
        }

        //
        // GET: /TargetContainer/Delete/5
 
        public ActionResult Delete(int id)
        {
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            return View(targetcontainer);
        }

        //
        // POST: /TargetContainer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            TargetContainer targetcontainer = db.TargetContainers.Find(id);
            db.TargetContainers.Remove(targetcontainer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AdminConsole/AdminConsole/Views/SiteMap/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script type="text/javascript">
</script>

<style type="text/css">
        iframe {
            position: absolute;
            height: 100%;
            border:none;
            margin:0px;
        }
    </style>

<table height="100%" width="100%">
    <tr>
        <td width="30%">
            <iframe id="sitemap" src="SiteMap/SiteMap" width="25%"> </iframe>
        </td>
        <td  width="70%">
            <iframe id="details" src="TargetContainer/Details" width="65%"> </iframe>
        </td>

    </tr>
</table>

AdminConsole/AdminConsole/Views/SiteMap/SiteMap.cshtml
@{
    Layout = null;
}
@model IEnumerable<AdminConsole.Models.Desktop>
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="@Url.Content("~/Content/treeview/jquery.treeview.css")" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/treeview/jquery.treeview.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/treeview/jquery.treeview.edit.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#browser").treeview();
        });
    </script>
</head>
<body>
    <h2>SiteMap</h2>

    <div id="content">
        <ul id="browser" class="filetree">
            @foreach (var item in Model)
            {
                <li>
                    <div>
                        @(item.Description)
                        @Html.ActionLink("Edit", "Edit", "Desktop", new { id = item.DesktopCode }, null)
                        @Html.ActionLink("New", "Create", "TargetContainer", new { desktopType = item.DesktopCode }, null)
                    </div>
                    @OrgTree(item.TargetContainers.Where(
                        (targetContainer) => targetContainer.ParentTargetContainer_Id == null))
                </li>
            }
        </ul>
    </div>
    @helper OrgTree(IEnumerable<AdminConsole.Models.TargetContainer> nodes)
        {
    if (nodes.Any())
    {
        <ul>
            @foreach (var node in nodes)
            {
                <li>
                    <div>
                        @Html.ActionLink(node.Description, "Details", "TargetContainer", new { id = node.Id }, new { @target = "details" });
                        @Html.ActionLink("Edit", "Edit", "TargetContainer", new { id = node.Id }, null)
                        @Html.ActionLink("New", "Create", "TargetContainer", new { desktopType = node.DesktopType_DesktopCode, parentContainerId = node.Id }, null)
                    </div>
                    @OrgTree(node.ChildTargetContainers)
                </li>
            }
        </ul>
    }
    }
</body>
</html>

AdminConsole/AdminConsole/Views/SiteMap/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Test</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>